### PR TITLE
about pombase + readme fix

### PR DESCRIPTION
**Pull request by manulera**
I have added the new Pombase about page, and I have fixed the instructions in the readme for making the static pages locally, although I am not sure that the `Update generated docs` section is used at all at this point. I guess now this is done when the code is pushed?

I just added a small change so far, to see if you think I have done it properly, then I can continue.

Best,
Manu

### CODE REVIEW

**Comment by kimrutherford** [comment]
> I have added the new Pombase about page,

Thanks.

> although I am not sure that the Update generated docs section is used at all at this point. I guess now this is done when the code is pushed?

That section is still useful if you need to re-create the HTML docs locally for testing.  But I think I need to improve the whole README because currently there isn't enough detail to set up everything.

> I just added a small change so far, to see if you think I have done it properly, then I can continue.

The changes to the about page look good.  I tried creating the documentation locally but it failed because of the two empty files (`about/collaborations.PomBase.md` and `documentation/getting-started.md`).

I fixed a bug in the [Markdown processing script](https://github.com/pombase/website/blob/new_static_pages/etc/process-markdown.pl) so that if reports the empty files better.  I then noticed that the CI wasn't reporting the error.  I fixed that too: https://github.com/pombase/website/runs/7981280214?check_suite_focus=true

**Comment by ValWood** [comment]
It isn't live though yet is it?

**Comment by manulera** [comment]
@ValWood 
> It isn't live though yet is it?

No, I had pushed one page only (about page) to verify that it worked, but there were some broken links (kind of). I have added dummy pages for Getting started and Collaborations that just say "Coming soon" just to verify everything is ok, then I can add the rest

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
> I have added dummy pages for Getting started and Collaborations that just say "Coming soon" just to verify everything is ok, then I can add the rest

Thanks Manu.  That fixed things: https://github.com/pombase/website/actions/runs/2926284561

**Comment by manulera** [comment]
Should I merge then?

**Comment by kimrutherford** [comment]
> Should I merge then?

I thought I would go ahead and merge the change so we could see it in the morning.

**Comment by ValWood** [comment]
Looks good!

**Comment by manulera** [comment]
I have deleted the branch

**Pull request merged**
