### PR TITLE
Rest of static pages added.

### PR DESCRIPTION
**Pull request by manulera**
Hi @kimrutherford, I have added the rest of the static pages that I wrote val in the doc. There are two things that I need your input on:

## Check the size of an icon

I have added an icon to the main text here: https://github.com/pombase/website/blob/322b3a55c103e29d647636672bda87fe6267599a/src/docs/documentation/getting-started.md?plain=1#L53

Not sure what the best sizing would be for it.

## Foldable content

We wanted some of the code to be foldable, I have labelled it with html comments:
https://github.com/pombase/website/blob/322b3a55c103e29d647636672bda87fe6267599a/src/docs/documentation/getting-started.md?plain=1#L55-L56

The idea is that it looks like in github: <details><summary>Read more</summary> the rest of the text</details>

In GitHub markdown, you can do this with this syntax:
```html
<details><summary>Read more</summary> the rest of the text</details>
```

Is there already a way of doing this in the markdown we are using? Otherwise, if you tell me which html tags you use for other collapsible in genes, I can just add plain html to the document.

### CODE REVIEW

**Comment by kimrutherford** [comment]
> Not sure what the best sizing would be for it.

I suggest something like:
```
style="width: 1em"
```
which gives the icon the width of an "m" character.  I like to use "em" as a measure in text blocks because it's proportional to the font size.

> Is there already a way of doing this in the markdown we are using?

I don't know of a Markdown way to do that.

> Otherwise, if you tell me which html tags you use for other collapsible in genes, I can just add plain html to the document.

Most of the sections like that on the website use Javascript to open and close.  

In the documentation you can probably use `<details>` and `<summary>` like:

```
<details>
<summary>A quick note on the names of genes:</summary>

The same gene may be known by different names. ...

</details>
```

The text inside the `<details>` can be normal Markdown syntax.

**Comment by kimrutherford** [comment]
> In GitHub markdown, you can do this with this syntax:

Sorry, I mis-read what you wrote.  The short answer is that we can use the same syntax.

**Comment by kimrutherford** [comment]
If you'd like to see what your changes will look like on the website, you can have a look at my desktop (until 1pm or so): https://desktop.kmr.nz/

**Comment by ValWood** [comment]
The new pages look good. I only. spotted on thing.  The. spacing between the GO and PHI-collaboration is a bit off.

@manu once it is live can you announce to pombelist, especially to announce. the "new user" pages to lab heads and encourage them to always send the link to new lab members.

**Comment by kimrutherford** [comment]
Hi @manulera

I had a look at the errors from the tests.  There are a bunch of warnings near the top that I have been meaning to fix, like this:

```
 Warning: src/app/front/front.component.html:114:92 - warning NG8107: The left side of this optional chain operation does not include 'null' or 'undefined' in its type, therefore the '?.' operator can be replaced with the '.' operator.

114   <div class="pombase-chado-json">Generated by {{metadata?.export_prog_name}} v{{metadata?.export_prog_version}}</div>
```

Please ignore those.  :-)

**Comment by manulera** [comment]
Hi Kim,

I think the error comes from those summary tags. They render properly in vscode's markdown but not with pandoc, at least I could not find the right settings. However, they don't return errors

**Comment by manulera** [comment]
Ok, I found the error, to isolate the problem:

```
pandoc src/docs/documentation/getting-started.md -f markdown-markdown_in_html_blocks -o dummy.html
```

using the pandoc format `markdown-markdown_in_html_blocks` produces this closing p tag before it should:
```
<p><details> <summary>Read how to make this query…</summary></p>
```

**Comment by manulera** [comment]
So I just decided to brute-force it: render the markdown in html with the usual `pandoc` markdown (not `markdown-markdown_in_html_blocks` flag), and then just copy-pasted the html sections. I added an extra file `getting-started-md-only.md` in case we want to edit in the future. It's easier to edit the markdown than the wild html.

I think this could be fixed in the future by not using the `markdown-markdown_in_html_blocks` flag, but given that this is probably rare and not using it may have unexpected consequences elsewhere, we can just do it like this whenever needed.

**Comment by kimrutherford** [comment]
Hi Manuel.  I think the HTML tags will all need to be at the start of the lines, with no spaces before them because of: https://pandoc.org/MANUAL.html#indented-code-blocks

**Comment by kimrutherford** [comment]
And it's probably best to leave a blank line before and after HTML.

Pandoc doesn't process this line properly:
```
![Top of gene page](assets/gene_page_top_part.png "Top of the gene page"){width="700"}
```

The `{width="700"}` isn't processed and ends up in the output HTML.

That will need to be:
```
![Top of gene page](assets/gene_page_top_part.png){width="700"}
```

**Comment by kimrutherford** [comment]
For testing the Markdown I use these two commands:

```bash
./etc/update_generated_files.sh ~/pombase-config/website/pombase_v2_config.json ~/pombase-curation/data_files/
node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build
```

To get that second command to work you'll need to install [node](https://nodejs.org/) and [npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) and then run this command once:
```
npm install
```

I'm happy to help if you'd like to try that.

**Comment by manulera** [comment]
Thanks for the details! I had seen the github action but was lazy about figuring out the right version of node and all (it was obviously the right thing to do). I just installed the dependencies and tested locally.

I see about the html tags. The problem with that is that then it is not possible to get the right indentation (having the foldable code inside the list), and not creating extra elements. We are a bit at the limit of markdown syntax, and I guess depending on the markdown processor used, it generates those errors (`-f markdown` does not make those unmatched tags). In summary, I ended up using html.

In the last push I fixed the caption of the image. I thought this was some special syntax, because there are other occurrences of this:

https://github.com/pombase/website/blob/d555ad89a484040e932847cdff6cc8fa17f0fcc9/src/docs/documentation/gene-page-modifications.md?plain=1#L13-L17

**Comment by manulera** [comment]
I added the extra instructions to check that the site can be built to the wiki:

https://github.com/pombase/website/wiki/Generating-documentation-HTML-after-Markdown-is-added-or-edited#checking-that-the-site-can-be-built

**Comment by kimrutherford** [comment]
Hi @manulera 

Is this ready to merge?  It looks good to me.  The changes are visible on my desktop: https://desktop.kmr.nz/documentation/getting-started

**Comment by manulera** [comment]
Hi @kimrutherford it all looks good, I made a small ammend, because these looked a bit weird (the foldable section was closer to the next item, rather than the item it was referring to):

Screenshot 2022-09-05 at 09 29 00

I have converted it into a list, so with PomBase styles applied, they should look like the others:

Screenshot 2022-09-05 at 09 30 17

If they do, we can merge.

**Comment by manulera** [comment]
Let's merge so that we can send an email with the new stuff. Will look alright either way!

**Comment by kimrutherford** [comment]
> Let's merge so that we can send an email with the new stuff. Will look alright either way!

Good plan.

I've checked-in a small fix to the CSS to add a bottom margin to details elements.  It changes this:

image

To look like this:

image

**Comment by manulera** [comment]
Yes! I had noticed in your site. Thanks!

**Pull request merged**
